# Generated by Django 4.0.4 on 2022-05-23 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('IT', 'IT'), ('DS', 'DS')], max_length=100, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('mopile', models.IntegerField(default=0, max_length=11)),
                ('idenNum', models.IntegerField(default=0, max_length=8)),
                ('email', models.EmailField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
